### ISSUE TITLE
Add a searchable "Administrator API"

### ISSUE THREAD

**Issue by waxzce** [CleverCloud/stream-dns#1]
with JWT token authentication, 

work started on a branch

**Comment by waxzce** [comment]
For known, the HTTP administrator server is exposed to the public without an authentication system.
A simple light way to fix this'll be to put a JWTas auth service.
A nice things could be to support more auth system like macaron, ... but JWT is a good first step.
For the public release I'll remove the administrator HTTP which has been develop mostly for our intern use case but I'll reput this when we have the auth JWT guard.

**Comment by NotBad4U** [comment]
With the merge of #17 and the update in README, we can now close this one.
