### ISSUE TITLE
Kafka support for SASL

### ISSUE THREAD

**Issue by waxzce** [CleverCloud/stream-dns#6]
his mechanism is not supported in the go libraries for Kafka.
Sarama the recommended lib by Confluent support only the SASL/PLAIN and OAUTHBEARER.

**Comment by NotBad4U** [comment]
With the merge https://github.com/Shopify/sarama/pull/1295 we can now add the support of SCRAM-SHA-512 and SCRAM-SHA-256 mechanismes :tada:

**Comment by NotBad4U** [comment]
with #14 we can now close this one.
